name: Build binaries

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: for ${{ matrix.network }} on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-2019
          - ubuntu-latest
        arch:
          - amd64
          - arm64
        network:
          - mainnet
          - fairground
    steps:
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
        id: npm

      - name: Set up Go ^1.19
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
        id: go

      - name: Install Wails dependencies
        if: ${{ runner.os == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.4.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Prepare ${{ matrix.network }} bundle
        if: ${{ runner.os == 'macOS' ||  runner.os == 'linux' }}
        run: |
          cat wails.${{ matrix.network }}.json > wails.json
          cat build/appicon.${{ matrix.network }}.png > build/appicon.png

      - name: Prepare ${{ matrix.network }} bundle
        if: ${{ runner.os == 'Windows' }}
        run: |
          type wails.${{ matrix.network }}.json > wails.json
          type build\appicon.${{ matrix.network }}.png > build\appicon.png

      - name: Build binary for Windows
        if: ${{ runner.os == 'Windows' }}
        env:
          VITE_FEATURE_MODE: ${{ matrix.network }}
        run: wails build -f -platform=windows/${{ matrix.arch }} -tags ${{ matrix.network }}

      - name: Build binary for macOS
        if: ${{ runner.os == 'macOS' }}
        env:
          VITE_FEATURE_MODE: ${{ matrix.network }}
        run: wails build -f -platform=darwin/${{ matrix.arch }} -tags ${{ matrix.network }}

      - name: Build binary for linux
        if: ${{ runner.os == 'linux' && matrix.arch == 'amd64' }}
        env:
          VITE_FEATURE_MODE: ${{ matrix.network }}
        run: wails build -f -platform=linux/${{ matrix.arch }} -tags ${{ matrix.network }}

      - name: Tests backend
        if: ${{ matrix.arch == 'amd64' }}
        run: go test -tags ${{ matrix.network }} -v ./...
